LEVEL_1 = [
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "B                                      B",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"]

LEVEL_2 = [
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "B                          B",
    "B                          B",
    "B                          B",
    "B                          B",
    "B                          B",
    "B                          B",
    "B                          B",
    "B                          B",
    "B                          B",
    "B                          B",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBB"
]
